"use client";

import { useState } from "react";
import { CeremonyEvent } from "@/lib/types";

interface InviteCardGeneratorProps {
  event: CeremonyEvent;
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString("en-UG", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function buildInviteText(
  guestName: string,
  event: CeremonyEvent,
  customMessage: string
): string {
  const dateStr = formatDate(event.date);
  const lines = [
    `💍 *You're Invited!*`,
    ``,
    `Dear *${guestName}*,`,
    ``,
    `We joyfully invite you to celebrate with us at:`,
    ``,
    `*${event.title}*`,
    `📅 ${dateStr}`,
    `📍 ${event.location}`,
    ``,
  ];

  if (customMessage.trim()) {
    lines.push(customMessage.trim());
    lines.push(``);
  }

  lines.push(`Your support means the world to us. 🙏`);
  lines.push(``);
  lines.push(`With love,`);
  lines.push(`*${event.organizer}*`);
  lines.push(``);
  lines.push(`_Invitation generated by CeremonyWallet 👛_`);

  return lines.join("\n");
}

export default function InviteCardGenerator({ event }: InviteCardGeneratorProps) {
  const [selectedContributor, setSelectedContributor] = useState<string>("custom");
  const [customName, setCustomName] = useState("");
  const [customMessage, setCustomMessage] = useState(
    "Thank you so much for your generous contribution to our special day. We are truly grateful for your love and support."
  );
  const [copiedFor, setCopiedFor] = useState<string | null>(null);

  // Build list of named contributors (non-anonymous)
  const namedContributors = event.contributions.filter((c) => !c.anonymous);

  const guestName =
    selectedContributor === "custom"
      ? customName
      : namedContributors.find((c) => c.id === selectedContributor)?.name ?? "";

  const inviteText = guestName.trim()
    ? buildInviteText(guestName.trim(), event, customMessage)
    : "";

  async function handleCopy(name: string, text: string) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
    }
    setCopiedFor(name);
    setTimeout(() => setCopiedFor(null), 2500);
  }

  function handleWhatsApp(text: string) {
    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, "_blank");
  }

  return (
    <div className="space-y-6">
      {/* Customise Message */}
      <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm space-y-4">
        <h2 className="text-lg font-bold text-gray-900">✏️ Customise Your Invitation</h2>

        {/* Personal Message */}
        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
            Personal Message
          </label>
          <textarea
            value={customMessage}
            onChange={(e) => setCustomMessage(e.target.value)}
            rows={3}
            className="w-full border border-gray-200 rounded-xl px-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-transparent text-sm resize-none"
            placeholder="Add a personal message to include in all invitations..."
          />
        </div>
      </div>

      {/* Send to All Contributors */}
      {namedContributors.length > 0 && (
        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 mb-1">
            📋 Send to Contributors
          </h2>
          <p className="text-sm text-gray-500 mb-4">
            Generate a personalised invitation for each person who contributed.
            Tap WhatsApp to send directly.
          </p>
          <div className="space-y-3">
            {namedContributors.map((contributor) => {
              const text = buildInviteText(contributor.name, event, customMessage);
              const isCopied = copiedFor === contributor.id;
              return (
                <div
                  key={contributor.id}
                  className="flex items-center justify-between p-4 rounded-xl bg-gray-50 border border-gray-100"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-pink-100 flex items-center justify-center text-pink-700 font-bold text-sm flex-shrink-0">
                      {contributor.name.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <p className="font-semibold text-gray-800 text-sm">
                        {contributor.name}
                      </p>
                      <p className="text-xs text-gray-400">
                        UGX {contributor.amount.toLocaleString()} ·{" "}
                        {contributor.status === "paid" ? "✅ Paid" : "⏳ Pledged"}
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-2 flex-shrink-0">
                    <button
                      onClick={() => handleCopy(contributor.id, text)}
                      className={`px-3 py-2 rounded-lg text-xs font-semibold transition-all ${
                        isCopied
                          ? "bg-green-500 text-white"
                          : "bg-white border border-gray-200 text-gray-600 hover:border-pink-300 hover:text-pink-600"
                      }`}
                    >
                      {isCopied ? "✅ Copied" : "📋 Copy"}
                    </button>
                    <button
                      onClick={() => handleWhatsApp(text)}
                      className="px-3 py-2 rounded-lg text-xs font-semibold bg-green-500 hover:bg-green-600 text-white transition-colors"
                    >
                      📱 WhatsApp
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Custom / One-off Invitation */}
      <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm space-y-4">
        <h2 className="text-lg font-bold text-gray-900">💌 Custom Invitation</h2>
        <p className="text-sm text-gray-500">
          Send an invitation to anyone — family, friends, or VIP guests.
        </p>

        <div>
          <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
            Guest Name
          </label>
          <input
            type="text"
            value={customName}
            onChange={(e) => setCustomName(e.target.value)}
            placeholder="e.g. Uncle Robert"
            className="w-full border border-gray-200 rounded-xl px-4 py-3 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-transparent text-sm"
          />
        </div>

        {/* Preview */}
        {inviteText && (
          <div className="bg-gradient-to-br from-pink-50 to-purple-50 rounded-xl p-4 border border-pink-100">
            <p className="text-xs font-semibold text-pink-700 uppercase tracking-wider mb-2">
              Preview
            </p>
            <pre className="text-xs text-gray-700 whitespace-pre-wrap leading-relaxed font-sans">
              {inviteText}
            </pre>
          </div>
        )}

        {inviteText && (
          <div className="flex gap-3">
            <button
              onClick={() => handleCopy("custom", inviteText)}
              className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm transition-all ${
                copiedFor === "custom"
                  ? "bg-green-500 text-white"
                  : "bg-purple-700 hover:bg-purple-800 text-white"
              }`}
            >
              {copiedFor === "custom" ? "✅ Copied!" : "📋 Copy Invitation"}
            </button>
            <button
              onClick={() => handleWhatsApp(inviteText)}
              className="flex-1 flex items-center justify-center gap-2 bg-green-500 hover:bg-green-600 text-white py-3 rounded-xl font-semibold text-sm transition-colors"
            >
              📱 Send on WhatsApp
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
