import type { InviteCardContent, InviteTemplateId } from "./types";
import { getInviteTemplate } from "./template-registry";

const SAMPLES: Record<InviteTemplateId, Partial<InviteCardContent>> = {
  royal: {
    name1: "Alex",
    name2: "Jordan",
    headline: "Wedding",
    date: "Saturday, 15 June 2026",
    time: "4:00 PM",
    venue: "Garden Venue",
    location: "Kampala",
    footer: "Reception to follow",
  },
  botanical: {
    name1: "Alex",
    name2: "Jordan",
    headline: "Celebration",
    subtitle: "An afternoon in the garden",
    date: "June 15, 2026",
    time: "2:00 PM",
    venue: "Botanical Gardens",
    location: "Entebbe",
    footer: "Light refreshments served",
  },
  pop: {
    name1: "SAM",
    name2: "RILEY",
    headline: "Birthday",
    tagline: "Let's party!",
    date: "SAT 15 JUN",
    time: "8 PM",
    venue: "Rooftop Lounge",
    location: "Kampala",
    footer: "Gifts optional",
  },
  minimal: {
    name1: "Alex Morgan",
    headline: "Gallery opening",
    hostLine: "You are invited",
    date: "15 June 2026",
    time: "6:00 PM",
    venue: "National Gallery",
    location: "Kampala",
    footer: "RSVP appreciated",
  },
  pastel: {
    name1: "Mia",
    name2: "Noah",
    headline: "Baby shower",
    subtitle: "Oh baby!",
    date: "Sunday, 20 July 2026",
    venue: "Sunshine Hall",
    location: "Jinja",
    footer: "Registry details on request",
  },
  cyber: {
    name1: "NODE_7",
    name2: "KERNEL",
    headline: "Launch night",
    tagline: "ACCESS GRANTED",
    hostLine: "Sector 9 HQ",
    date: "2088.06.15",
    time: "00:00 UTC",
    venue: "Neon District",
    location: "Grid 12",
    footer: "Bring your passcode",
  },
  memorial: {
    headline: "In loving Memory of",
    name1: "Jack Wilson",
    subtitle: "Jun 19 1953",
    tagline: "Aug 7 2018",
    date: "19th August 2018",
    venue: "Olive Church",
    location: "2700 Norman Gate\nOhio DH 975.",
    font: "serif",
    accentColor: "#D4AF37",
  },
  heritage: {
    headline: "IN LOVING MEMORY",
    name1: "Jane Smith",
    subtitle: "JANUARY 18, 1990 - OCTOBER 15, 2030",
    tagline: "BURIAL SERVICE",
    date: "OCTOBER 22",
    time: "2 PM",
    location: "79 HICKORY LANE VIENNA, DC 22182",
    hostLine: "DONA J. NELSON",
    footer: "202-455-1993\nDONAJNELSON@RHYTA.COM",
    font: "serif",
    accentColor: "#B89966",
  },
  celebrate: {
    headline: "YOU ARE INVITED TO CELEBRATE",
    name1: "Caroline's",
    tagline: "5TH BIRTHDAY",
    date: "SATURDAY AUGUST 8",
    time: "11 AM 1 PM",
    venue: "SHADY GROVE PARK",
    location: "SHELTER B",
    footer: "RSVP TO SHARON AT 123.456.7890",
    font: "sans-serif",
    accentColor: "#48B5A3",
  },
  savedate: {
    name1: "Groom's Name",
    name2: "Bride's Name",
    subtitle: "JOYFULLY INVITES YOU TO JOIN",
    tagline: "THEIR WEDDING CELEBRATION",
    date: "2024-05-27",
    time: "5 O'CLOCK IN THE EVENING",
    venue: "Hotel's Name",
    location: "Hotel's Address",
    font: "serif",
    accentColor: "#D4AF37",
  },
  gala: {
    hostLine: "ROBERTSON & SMITH INC.",
    subtitle: "CORDIALLY INVITES YOU TO A",
    tagline: "24th Annual",
    headline: "FUNDRAISER",
    date: "FRIDAY,",
    time: "NOVEMBER 20TH AT 8:00 PM",
    venue: "HOTEL / VENUE NAME",
    location: "445, MOUNT EDEN ROAD, ANYTOWN, USA",
    ceremonyNote: "Join us for Dinner & Dancing",
    footer: "LOREM TO SUE SMITH AT 01234 552 116\nBY NOVEMBER 10TH",
    font: "sans-serif",
    accentColor: "#D4AF37",
  },
};

export function themeSampleContent(
  templateId: InviteTemplateId | string
): InviteCardContent {
  const def = getInviteTemplate(templateId);
  const partial = SAMPLES[def.id as InviteTemplateId] ?? SAMPLES.royal;
  return {
    name1: "",
    name2: "",
    headline: "Celebration",
    date: "",
    time: "",
    venue: "",
    location: "",
    footer: "",
    font: "serif",
    accentColor: def.palette.accent,
    rsvpEnabled: true,
    ...partial,
  };
}

/** @deprecated Use themeSampleContent(templateId) */
export const THEME_SAMPLE_CONTENT: InviteCardContent = themeSampleContent("royal");
