"use client";

import { useState } from "react";
import { Contribution } from "@/lib/types";

interface ContributionReceiptProps {
  eventTitle: string;
  eventDate: string;
  eventLocation: string;
  contributions: Contribution[];
  raisedAmount: number;
  targetAmount: number;
}

function formatUGX(amount: number) {
  return `UGX ${amount.toLocaleString("en-UG")}`;
}

function buildReceiptText(
  eventTitle: string,
  eventDate: string,
  eventLocation: string,
  contributions: Contribution[],
  raisedAmount: number,
  targetAmount: number
): string {
  const dateStr = new Date(eventDate).toLocaleDateString("en-UG", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const lines: string[] = [
    `📋 CONTRIBUTION RECEIPT`,
    `━━━━━━━━━━━━━━━━━━━━━━━━`,
    `Event: ${eventTitle}`,
    `Date: ${dateStr}`,
    `Location: ${eventLocation}`,
    `━━━━━━━━━━━━━━━━━━━━━━━━`,
    ``,
    `CONTRIBUTIONS (${contributions.length} total):`,
    ``,
  ];

  contributions.forEach((c, i) => {
    const name = c.anonymous ? "Anonymous" : c.name;
    const status = c.status === "paid" ? "✅ Paid" : "⏳ Pledged";
    lines.push(`${i + 1}. ${name}`);
    lines.push(`   Amount: ${formatUGX(c.amount)} — ${status}`);
    if (c.message) lines.push(`   "${c.message}"`);
  });

  lines.push(``);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`Total Raised: ${formatUGX(raisedAmount)}`);
  lines.push(`Target: ${formatUGX(targetAmount)}`);
  lines.push(
    `Progress: ${Math.min(Math.round((raisedAmount / targetAmount) * 100), 100)}%`
  );
  lines.push(``);
  lines.push(`Generated by CeremonyWallet 👛`);

  return lines.join("\n");
}

export default function ContributionReceipt({
  eventTitle,
  eventDate,
  eventLocation,
  contributions,
  raisedAmount,
  targetAmount,
}: ContributionReceiptProps) {
  const [copied, setCopied] = useState(false);

  const receiptText = buildReceiptText(
    eventTitle,
    eventDate,
    eventLocation,
    contributions,
    raisedAmount,
    targetAmount
  );

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(receiptText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback for older browsers
      const el = document.createElement("textarea");
      el.value = receiptText;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  }

  function handleWhatsApp() {
    const encoded = encodeURIComponent(receiptText);
    window.open(`https://wa.me/?text=${encoded}`, "_blank");
  }

  return (
    <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-gray-900">📋 Contribution Receipt</h2>
        <span className="text-xs text-gray-400 bg-gray-50 px-2 py-1 rounded-full">
          {contributions.length} contributors
        </span>
      </div>

      <p className="text-sm text-gray-500 mb-4">
        Copy and share this receipt to show everyone exactly who contributed and
        how much — full transparency, no disputes.
      </p>

      {/* Receipt Preview */}
      <div className="bg-gray-50 rounded-xl p-4 mb-4 font-mono text-xs text-gray-700 whitespace-pre-wrap leading-relaxed max-h-48 overflow-y-auto border border-gray-200">
        {receiptText}
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3">
        <button
          onClick={handleCopy}
          className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-xl font-semibold text-sm transition-all ${
            copied
              ? "bg-green-500 text-white"
              : "bg-purple-700 hover:bg-purple-800 text-white"
          }`}
        >
          {copied ? (
            <>✅ Copied!</>
          ) : (
            <>📋 Copy Receipt</>
          )}
        </button>
        <button
          onClick={handleWhatsApp}
          className="flex-1 flex items-center justify-center gap-2 bg-green-500 hover:bg-green-600 text-white py-3 rounded-xl font-semibold text-sm transition-colors"
        >
          <span>📱</span> Share on WhatsApp
        </button>
      </div>
    </div>
  );
}
